parameters:
    draw.swagger.class: Draw\Swagger\Swagger
    draw.swagger.extrator.php_doc_operation_exractor.class: Draw\Swagger\Extraction\Extractor\PhpDocOperationExtractor
    draw.swagger.extrator.jms_extractor.class: Draw\Swagger\Extraction\Extractor\JmsExtractor
    draw.swagger.extrator.symfony_container_swagger_extractor.class: Draw\SwaggerBundle\Extractor\SymfonyContainerSwaggerExtractor
    draw.swagger.extrator.fos_rest_route_operation_extractor.class: Draw\SwaggerBundle\Extractor\FOSRestRouteOperationExtractor
    draw.swagger.extrator.route_operation_extractor.class: Draw\SwaggerBundle\Extractor\RouteOperationExtractor

services:
    draw.swagger:
        class: %draw.swagger.class%
        arguments: [@jms_serializer.serializer]

    draw.swagger.extrator.symfony_container_swagger_extractor:
        class: %draw.swagger.extrator.symfony_container_swagger_extractor.class%
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.php_doc_operation_exractor:
        class: %draw.swagger.extrator.php_doc_operation_exractor.class%
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.route_operation_extractor:
        class: %draw.swagger.extrator.route_operation_extractor.class%
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.fos_rest_route_operation_extractor:
        class: %draw.swagger.extrator.fos_rest_route_operation_extractor.class%
        arguments: [@fos_rest.request.param_fetcher.reader]
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.jms_extractor:
        class: %draw.swagger.extrator.jms_extractor.class%
        arguments: [@jms_serializer.metadata_factory, @jms_serializer.naming_strategy]
        tags:
            - { name: swagger.extractor }

    draw.swagger.jms_serializer_listener:
        class: Draw\Swagger\JMSSerializerListener
        tags:
            - { name: jms_serializer.event_subscriber }
